import image1 from "./assets/images/image1.png";
import image2 from "./assets/images/image2.png";
import image3 from "./assets/images/image3.png";
import image4 from "./assets/images/image4.png";
import bg1 from "./assets/homePage/bannerPics/bg1.jpg";
import bg2 from "./assets/homePage/bannerPics/bg2.jpg";
import bg3 from "./assets/homePage/bannerPics/bg3.jpg";
import bg4 from "./assets/homePage/bannerPics/bg4.jpg";
import bg5 from "./assets/homePage/bannerPics/bg5.jpg";
import bg6 from "./assets/homePage/bannerPics/bg6.jpg";

export const allMovies = [
  {
    id: 1,
    title: "Inception",
    genre: "Sci-Fi",
    releaseYear: 2010,
    rating: 8.8,
    thumbnail: bg3,
    totalTime: "2h 27m",
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    trailerUrl: "https://www.youtube.com/watch?v=8hP9D6kZseM",
  },
  {
    id: 2,
    title: "The Dark Knight",
    genre: "Action",
    releaseYear: 2008,
    rating: 9.0,
    thumbnail: bg1,
    totalTime: "2h 27m",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
  },
  {
    id: 3,
    title: "The Shawshank Redemption",
    genre: "Drama",
    releaseYear: 1994,
    rating: 9.3,
    thumbnail: bg2,
    totalTime: "2h 27m",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    trailerUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    id: 4,
    title: "Pulp Fiction",
    genre: "Crime",
    releaseYear: 1994,
    rating: 8.9,
    thumbnail: bg4,
    totalTime: "2h 27m",
    description:
      "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    trailerUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
  },
  {
    id: 5,
    title: "The Matrix",
    genre: "Sci-Fi",
    releaseYear: 1999,
    rating: 8.7,
    thumbnail: bg5,
    totalTime: "2h 27m",
    description:
      "A computer programmer discovers that reality as he knows it is a simulation created by machines, and he joins a group of rebels to break free from their control.",
    trailerUrl: "https://www.youtube.com/watch?v=m8e-FF8MsqU",
  },
  {
    id: 6,
    title: "Interstellar",
    genre: "Sci-Fi",
    releaseYear: 2014,
    rating: 8.6,
    thumbnail: bg6,
    totalTime: "2h 27m",
    description:
      "A team of astronauts embarks on a journey through a wormhole in search of a new habitable planet as Earth faces a global food crisis.",
    trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
  },
  {
    id: 7,
    title: "The Godfather",
    genre: "Crime",
    releaseYear: 1972,
    rating: 9.2,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
  },
  {
    id: 8,
    title: "Forrest Gump",
    genre: "Drama",
    releaseYear: 1994,
    rating: 8.8,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
    trailerUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
  },
  {
    id: 9,
    title: "Gladiator",
    genre: "Action",
    releaseYear: 2000,
    rating: 8.5,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
    trailerUrl: "https://www.youtube.com/watch?v=owK1qxDselE",
  },
  {
    id: 10,
    title: "The Lord of the Rings: The Return of the King",
    genre: "Fantasy",
    releaseYear: 2003,
    rating: 8.9,
    thumbnail: image4,
    totalTime: "2h 27m",
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    trailerUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
  },
  {
    id: 11,
    title: "The Revenant",
    genre: "Adventure",
    releaseYear: 2015,
    rating: 8.0,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
    trailerUrl: "https://www.youtube.com/watch?v=LoebZZ8K5N0",
  },
  {
    id: 12,
    title: "Mad Max: Fury Road",
    genre: "Action",
    releaseYear: 2015,
    rating: 8.1,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
    trailerUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
  },
  {
    id: 13,
    title: "Joker",
    genre: "Crime",
    releaseYear: 2019,
    rating: 8.4,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
    trailerUrl: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
  },
  {
    id: 14,
    title: "Parasite",
    genre: "Comedy",
    releaseYear: 2019,
    rating: 8.6,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    trailerUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
  },
  {
    id: 15,
    title: "1917",
    genre: "Drama",
    releaseYear: 2019,
    rating: 8.3,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldier's brothers, from walking straight into a deadly trap.",
    trailerUrl: "https://www.youtube.com/watch?v=YqNYrYUiMfg",
  },
  {
    id: 16,
    title: "Knives Out",
    genre: "Crime",
    releaseYear: 2019,
    rating: 7.9,
    thumbnail: image4,
    totalTime: "2h 27m",
    description:
      "A detective investigates the death of a patriarch of an eccentric, combative family.",
    trailerUrl: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
  },
  {
    id: 17,
    title: "Once Upon a Time in Hollywood",
    genre: "Comedy",
    releaseYear: 2019,
    rating: 7.6,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.",
    trailerUrl: "https://www.youtube.com/watch?v=ELeMaP8EPAA",
  },
  {
    id: 18,
    title: "Ford v Ferrari",
    genre: "Action",
    releaseYear: 2019,
    rating: 8.1,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
    trailerUrl: "https://www.youtube.com/watch?v=I3h9Z89U9ZA",
  },
  {
    id: 19,
    title: "Breaking Bad",
    genre: "Crime",
    releaseYear: 2008,
    rating: 9.5,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "A high school chemistry teacher turned methamphetamine manufacturing drug dealer navigates the dangerous criminal underworld.",
    trailerUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
  },
  {
    id: 20,
    title: "Friends",
    genre: "Comedy",
    releaseYear: 1994,
    rating: 8.5,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "Follows the lives of six young adults living in Manhattan, New York.",
    trailerUrl: "https://www.youtube.com/watch?v=hDNNmeeJs1Q",
  },
  {
    id: 21,
    title: "Game of Thrones",
    genre: "Action",
    releaseYear: 2011,
    rating: 9.3,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    trailerUrl: "https://www.youtube.com/watch?v=rlR4PJn8b8I",
  },
  {
    id: 22,
    title: "The Witcher",
    genre: "Action",
    releaseYear: 2019,
    rating: 8.2,
    thumbnail: image4,
    totalTime: "2h 27m",
    description:
      "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
    trailerUrl: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
  },
  {
    id: 23,
    title: "Narcos",
    genre: "Biography",
    releaseYear: 2015,
    rating: 8.8,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
    trailerUrl: "https://www.youtube.com/watch?v=U7elNhHwgBU",
  },
  {
    id: 24,
    title: "Stranger Things",
    genre: "Sci-Fi",
    releaseYear: 2016,
    rating: 8.7,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
    trailerUrl: "https://www.youtube.com/watch?v=XWxyRG_tckY",
  },
  {
    id: 25,
    title: "Avengers: Endgame",
    genre: "Action",
    releaseYear: 2019,
    rating: 8.4,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos' actions and restore order to the universe.",
    trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
  },
  {
    id: 26,
    title: "Spider-Man: Into the Spider-Verse",
    genre: "Animation",
    releaseYear: 2018,
    rating: 8.4,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
    trailerUrl: "https://www.youtube.com/watch?v=g4Hbz2jLxvQ",
  },
  {
    id: 27,
    title: "Black Panther",
    genre: "Action",
    releaseYear: 2018,
    rating: 7.3,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and confront a challenger from his country's past.",
    trailerUrl: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
  },
  {
    id: 28,
    title: "Wonder Woman",
    genre: "Action",
    releaseYear: 2017,
    rating: 7.4,
    thumbnail: image4,
    totalTime: "2h 27m",
    description:
      "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
    trailerUrl: "https://www.youtube.com/watch?v=VSB4wGIdDwo",
  },
  {
    id: 29,
    title: "Jumanji: Welcome to the Jungle",
    genre: "Action",
    releaseYear: 2017,
    rating: 6.9,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
    trailerUrl: "https://www.youtube.com/watch?v=2QKg5SZ_35I",
  },
  {
    id: 30,
    title: "Guardians of the Galaxy",
    genre: "Action",
    releaseYear: 2014,
    rating: 8.0,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
    trailerUrl: "https://www.youtube.com/watch?v=d96cjJhvlMA",
  },
  {
    id: 31,
    title: "The Godfather",
    genre: "Crime",
    releaseYear: 1972,
    rating: 9.2,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
  },
  {
    id: 32,
    title: "The Shawshank Redemption",
    genre: "Drama",
    releaseYear: 1994,
    rating: 9.3,
    thumbnail: image4,
    totalTime: "2h 27m",
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    trailerUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
  },
  {
    id: 33,
    title: "The Dark Knight",
    genre: "Action",
    releaseYear: 2008,
    rating: 9.0,
    thumbnail: image1,
    totalTime: "2h 27m",
    description:
      "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
  },
  {
    id: 34,
    title: "Schindler's List",
    genre: "Biography",
    releaseYear: 1993,
    rating: 8.9,
    thumbnail: image2,
    totalTime: "2h 27m",
    description:
      "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
    trailerUrl: "https://www.youtube.com/watch?v=gG22XNhtnoY",
  },
  {
    id: 35,
    title: "The Lord of the Rings: The Return of the King",
    genre: "Fantasy",
    releaseYear: 2003,
    rating: 8.9,
    thumbnail: image3,
    totalTime: "2h 27m",
    description:
      "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
    trailerUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
  },
  {
    id: 36,
    title: "Fight Club",
    genre: "Drama",
    releaseYear: 1999,
    rating: 8.8,
    thumbnail: 4,
    totalTime: "2h 27m",
    description:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    trailerUrl: "https://www.youtube.com/watch?v=BdJKm16Co6M",
  },
];

export const sections = {
  trending: [
    {
      id: 1,
      title: "Inception",
      genre: "Sci-Fi",
      releaseYear: 2010,
      rating: 8.8,
      thumbnail: bg3,
      totalTime: "2h 27m",
      description:
        "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
      trailerUrl: "https://www.youtube.com/watch?v=8hP9D6kZseM",
    },
    {
      id: 2,
      title: "The Dark Knight",
      genre: "Action",
      releaseYear: 2008,
      rating: 9.0,
      thumbnail: bg1,
      totalTime: "2h 27m",
      description:
        "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    },
    {
      id: 3,
      title: "The Shawshank Redemption",
      genre: "Drama",
      releaseYear: 1994,
      rating: 9.3,
      thumbnail: bg2,
      totalTime: "2h 27m",
      description:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      trailerUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    },
    {
      id: 4,
      title: "Pulp Fiction",
      genre: "Crime",
      releaseYear: 1994,
      rating: 8.9,
      thumbnail: bg4,
      totalTime: "2h 27m",
      description:
        "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
      trailerUrl: "https://www.youtube.com/watch?v=s7EdQ4FqbhY",
    },
    {
      id: 5,
      title: "The Matrix",
      genre: "Sci-Fi",
      releaseYear: 1999,
      rating: 8.7,
      thumbnail: bg5,
      totalTime: "2h 27m",
      description:
        "A computer programmer discovers that reality as he knows it is a simulation created by machines, and he joins a group of rebels to break free from their control.",
      trailerUrl: "https://www.youtube.com/watch?v=m8e-FF8MsqU",
    },
    {
      id: 6,
      title: "Interstellar",
      genre: "Sci-Fi",
      releaseYear: 2014,
      rating: 8.6,
      thumbnail: bg6,
      totalTime: "2h 27m",
      description:
        "A team of astronauts embarks on a journey through a wormhole in search of a new habitable planet as Earth faces a global food crisis.",
      trailerUrl: "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    },
  ],
  topMoviesForYou: [
    {
      id: 7,
      title: "The Godfather",
      genre: "Crime",
      releaseYear: 1972,
      rating: 9.2,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
    },
    {
      id: 8,
      title: "Forrest Gump",
      genre: "Drama",
      releaseYear: 1994,
      rating: 8.8,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
      trailerUrl: "https://www.youtube.com/watch?v=bLvqoHBptjg",
    },
    {
      id: 9,
      title: "Gladiator",
      genre: "Action",
      releaseYear: 2000,
      rating: 8.5,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
      trailerUrl: "https://www.youtube.com/watch?v=owK1qxDselE",
    },
    {
      id: 10,
      title: "The Lord of the Rings: The Return of the King",
      genre: "Fantasy",
      releaseYear: 2003,
      rating: 8.9,
      thumbnail: image4,
      totalTime: "2h 27m",
      description:
        "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      trailerUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
    },
    {
      id: 11,
      title: "The Revenant",
      genre: "Adventure",
      releaseYear: 2015,
      rating: 8.0,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team.",
      trailerUrl: "https://www.youtube.com/watch?v=LoebZZ8K5N0",
    },
    {
      id: 12,
      title: "Mad Max: Fury Road",
      genre: "Action",
      releaseYear: 2015,
      rating: 8.1,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.",
      trailerUrl: "https://www.youtube.com/watch?v=hEJnMQG9ev8",
    },
  ],
  recentReleases: [
    {
      id: 13,
      title: "Joker",
      genre: "Crime",
      releaseYear: 2019,
      rating: 8.4,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.",
      trailerUrl: "https://www.youtube.com/watch?v=zAGVQLHvwOY",
    },
    {
      id: 14,
      title: "Parasite",
      genre: "Comedy",
      releaseYear: 2019,
      rating: 8.6,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
      trailerUrl: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    },
    {
      id: 15,
      title: "1917",
      genre: "Drama",
      releaseYear: 2019,
      rating: 8.3,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "Two young British soldiers during the First World War are given an impossible mission: deliver a message deep in enemy territory that will stop 1,600 men, and one of the soldier's brothers, from walking straight into a deadly trap.",
      trailerUrl: "https://www.youtube.com/watch?v=YqNYrYUiMfg",
    },
    {
      id: 16,
      title: "Knives Out",
      genre: "Crime",
      releaseYear: 2019,
      rating: 7.9,
      thumbnail: image4,
      totalTime: "2h 27m",
      description:
        "A detective investigates the death of a patriarch of an eccentric, combative family.",
      trailerUrl: "https://www.youtube.com/watch?v=qGqiHJTsRkQ",
    },
    {
      id: 17,
      title: "Once Upon a Time in Hollywood",
      genre: "Comedy",
      releaseYear: 2019,
      rating: 7.6,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.",
      trailerUrl: "https://www.youtube.com/watch?v=ELeMaP8EPAA",
    },
    {
      id: 18,
      title: "Ford v Ferrari",
      genre: "Action",
      releaseYear: 2019,
      rating: 8.1,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "American car designer Carroll Shelby and driver Ken Miles battle corporate interference and the laws of physics to build a revolutionary race car for Ford in order to defeat Ferrari at the 24 Hours of Le Mans in 1966.",
      trailerUrl: "https://www.youtube.com/watch?v=I3h9Z89U9ZA",
    },
  ],
  yourWatches: [
    {
      id: 19,
      title: "Breaking Bad",
      genre: "Crime",
      releaseYear: 2008,
      rating: 9.5,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "A high school chemistry teacher turned methamphetamine manufacturing drug dealer navigates the dangerous criminal underworld.",
      trailerUrl: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    },
    {
      id: 20,
      title: "Friends",
      genre: "Comedy",
      releaseYear: 1994,
      rating: 8.5,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "Follows the lives of six young adults living in Manhattan, New York.",
      trailerUrl: "https://www.youtube.com/watch?v=hDNNmeeJs1Q",
    },
    {
      id: 21,
      title: "Game of Thrones",
      genre: "Action",
      releaseYear: 2011,
      rating: 9.3,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
      trailerUrl: "https://www.youtube.com/watch?v=rlR4PJn8b8I",
    },
    {
      id: 22,
      title: "The Witcher",
      genre: "Action",
      releaseYear: 2019,
      rating: 8.2,
      thumbnail: image4,
      totalTime: "2h 27m",
      description:
        "Geralt of Rivia, a solitary monster hunter, struggles to find his place in a world where people often prove more wicked than beasts.",
      trailerUrl: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
    },
    {
      id: 23,
      title: "Narcos",
      genre: "Biography",
      releaseYear: 2015,
      rating: 8.8,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar.",
      trailerUrl: "https://www.youtube.com/watch?v=U7elNhHwgBU",
    },
    {
      id: 24,
      title: "Stranger Things",
      genre: "Sci-Fi",
      releaseYear: 2016,
      rating: 8.7,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "When a young boy disappears, his mother, a police chief, and his friends must confront terrifying supernatural forces in order to get him back.",
      trailerUrl: "https://www.youtube.com/watch?v=XWxyRG_tckY",
    },
  ],
  trendingMovies: [
    {
      id: 25,
      title: "Avengers: Endgame",
      genre: "Action",
      releaseYear: 2019,
      rating: 8.4,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to undo Thanos' actions and restore order to the universe.",
      trailerUrl: "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    },
    {
      id: 26,
      title: "Spider-Man: Into the Spider-Verse",
      genre: "Animation",
      releaseYear: 2018,
      rating: 8.4,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "Teen Miles Morales becomes the Spider-Man of his universe, and must join with five spider-powered individuals from other dimensions to stop a threat for all realities.",
      trailerUrl: "https://www.youtube.com/watch?v=g4Hbz2jLxvQ",
    },
    {
      id: 27,
      title: "Black Panther",
      genre: "Action",
      releaseYear: 2018,
      rating: 7.3,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "T'Challa, heir to the hidden but advanced kingdom of Wakanda, must step forward to lead his people into a new future and confront a challenger from his country's past.",
      trailerUrl: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    },
    {
      id: 28,
      title: "Wonder Woman",
      genre: "Action",
      releaseYear: 2017,
      rating: 7.4,
      thumbnail: image4,
      totalTime: "2h 27m",
      description:
        "When a pilot crashes and tells of conflict in the outside world, Diana, an Amazonian warrior in training, leaves home to fight a war, discovering her full powers and true destiny.",
      trailerUrl: "https://www.youtube.com/watch?v=VSB4wGIdDwo",
    },
    {
      id: 29,
      title: "Jumanji: Welcome to the Jungle",
      genre: "Action",
      releaseYear: 2017,
      rating: 6.9,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "Four teenagers are sucked into a magical video game, and the only way they can escape is to work together to finish the game.",
      trailerUrl: "https://www.youtube.com/watch?v=2QKg5SZ_35I",
    },
    {
      id: 30,
      title: "Guardians of the Galaxy",
      genre: "Action",
      releaseYear: 2014,
      rating: 8.0,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
      trailerUrl: "https://www.youtube.com/watch?v=d96cjJhvlMA",
    },
  ],
  topRated: [
    {
      id: 31,
      title: "The Godfather",
      genre: "Crime",
      releaseYear: 1972,
      rating: 9.2,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
      trailerUrl: "https://www.youtube.com/watch?v=sY1S34973zA",
    },
    {
      id: 32,
      title: "The Shawshank Redemption",
      genre: "Drama",
      releaseYear: 1994,
      rating: 9.3,
      thumbnail: image4,
      totalTime: "2h 27m",
      description:
        "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
      trailerUrl: "https://www.youtube.com/watch?v=6hB3S9bIaco",
    },
    {
      id: 33,
      title: "The Dark Knight",
      genre: "Action",
      releaseYear: 2008,
      rating: 9.0,
      thumbnail: image1,
      totalTime: "2h 27m",
      description:
        "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
      trailerUrl: "https://www.youtube.com/watch?v=EXeTwQWrcwY",
    },
    {
      id: 34,
      title: "Schindler's List",
      genre: "Biography",
      releaseYear: 1993,
      rating: 8.9,
      thumbnail: image2,
      totalTime: "2h 27m",
      description:
        "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
      trailerUrl: "https://www.youtube.com/watch?v=gG22XNhtnoY",
    },
    {
      id: 35,
      title: "The Lord of the Rings: The Return of the King",
      genre: "Fantasy",
      releaseYear: 2003,
      rating: 8.9,
      thumbnail: image3,
      totalTime: "2h 27m",
      description:
        "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.",
      trailerUrl: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
    },
    {
      id: 36,
      title: "Fight Club",
      genre: "Drama",
      releaseYear: 1999,
      rating: 8.8,
      thumbnail: 4,
      totalTime: "2h 27m",
      description:
        "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
      trailerUrl: "https://www.youtube.com/watch?v=BdJKm16Co6M",
    },
  ],
};
